### ISSUE TITLE
Using with AudioWorklet?

### ISSUE THREAD

**Issue by Catsvilles** [sebpiq/paulstretch.js#3]
Hey, I'm curious to try and use paulstretch.js but since ScriptProcessorNode is deprecated what would be the easiest way to use paulstretch.js with AudioWorklet? 

In your opinion, could we somehow use it on AudioBuffer simply calling it with AudioWorklet class or the whole project must be rewritten to extend `AudioWorkletProcessor` and the calculations should be in `process()` function? Maybe you have some examples? Thank you! :)

**Comment by sebpiq** [comment]
Hi @Catsvilles ! The lib is actually implemented as a simple class which has methods to do the processing :

```
paulStretch = new PaulStretch(numberOfChannels, ratio, winSize)
paulStretch.write(data)
paulStretch.process()
paulStretch.read(arrayOut)
```
Therefore, there is nothing stopping you right now to put it in an AudioWorklet. Please let me know if you do it! I'd be happy to see it in action, and why not adding it as an example to the repo :)

**Comment by Catsvilles** [comment]
@sebpiq Thanks for getting back to me! Absolutely, if I will hack this together one of those days I will submit pr or something :)
